# // docker-compose.yaml
version: '3.8'
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    ports:
      - "18080:18080"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    ports:
      - "3000:3000"
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
